---

###
### Debian apt repositories
###
apt_repo_repositories:
  - file: debian-main
    repo: deb http://ftp.de.debian.org/debian/ stretch main
  - file: debian-updates
    repo: deb http://ftp.de.debian.org/debian/ stretch-updates main
  - file: debian-security
    repo: deb http://security.debian.org/debian-security stretch/updates main


###
### System Python versions
###
python_2: yes
python_3: yes
python_default: 2


###
### Debian packages (add your custom packages here)
###
apt_packages: []


###
### Python pip packages (add your custom packages here)
###
pip_packages: []


###
### Select packages to install
###
### 'install': Install the package
### 'remove':  Uninstall the package
### Any other value will ignore the package (neither install nor uninstall)

chromium:             'ignore'
clipmenu:             'ignore'
diff_highlight:       'ignore'
docker:               'ignore'
docker_compose:       'ignore'
font_font_awesome:    'ignore'
font_droid_sans_mono: 'ignore'
font_san_francisco:   'ignore'
font_terminus:        'ignore'
font_ubuntu:          'ignore'
fzf:                  'ignore'
hipchat:              'ignore'
i3_gaps:              'ignore'
i3_utils_bin:         'ignore'
i3_utils_systemd:     'ignore'
i3blocks_modules:     'ignore'
icon_moka:            'ignore'
lxdm:                 'ignore'
neovim:               'ignore'
packer:               'ignore'
ranger:               'ignore'
skype:                'ignore'
sublime:              'ignore'
sxiv:                 'ignore'
telegram:             'ignore'
theme_arc:            'ignore'
thunar:               'ignore'
xbacklight:           'ignore'
xorg:                 'ignore'
zathura:              'ignore'


###
### Settings for packages
###

# ---- Docker ----
# 'wheezy', 'jessie', 'stretch' or 'buster'
docker_repo_dist: stretch
# 'stable' or 'edge'
docker_repo_channel: stable

# ---- FZF ----
# Add sourcing ~/.fzf.bash to your normal shell config?
fzf_update_rc: Yes
# Enable/Disable fuzzy completion (bash & zsh)?
fzf_completion: No
# Enable/disable key bindings (CTRL-T, CTRL-R, ALT-C)?
fzf_key_bindings: No

# ---- HipChat ----
# 'wheezy', 'jessie', 'stretch' or 'buster'
hipchat_repo_dist: stretch

# ---- LXDM ----
lxdm_dpi: 96
lxdm_gtk_theme: Industrial
lxdm_show_user_list: no

# ---- Skype ----
# 'stable' or 'unstable'
skype_repo_channel: stable

# ---- Sublime ----
# 'stable' or 'dev'
sublime_repo_channel: stable

# ---- sxiv ----
# Make sxiv default program for pictures
sxiv_default_image_viewer: yes

# ---- Thunar ----
thunar_volman_enable: yes
thunar_archive_plugin_enable: yes

# ---- Xorg ----
# Supported values: 'amdgpu' 'ati' 'intel' 'modesetting' 'nouveau' 'nvidia' 'radeon'
xorg_gpu: modesetting
# Supported values: 'XAA' 'EXA' 'UXA' 'SNA' 'glamor'
xorg_gpu_accel_method: glamor
# Enable VDPAU_DRIVER=va_gl systemwide
xorg_gpu_vdpau_va_gl_enable: yes
# 'libinput' or 'synaptics'
xorg_touchpad_enable: yes
xorg_touchpad_driver: 'synaptics'


###
### Set your preferred default applications
###
xdg_mime_defaults:
  - desktop_file: Thunar.desktop
    mime_types:
      - inode/directory
  - desktop_file: chromium.desktop
    mime_types:
      - text/html
      - text/xml
      - application/xhtml_xml
      - application/x-mimearchive
      - x-scheme-handler/http
      - x-scheme-handler/https
