sudo: required

language: python

services:
  - docker

env:
  matrix:
    # Default Debian profile
    - random=0 dist=debian-stretch
    - random=1 dist=debian-stretch
    - random=0 dist=debian-testing
    - random=1 dist=debian-testing
    # Cytopia's profile
    - random=0 dist=cytopia-stretch
    - random=1 dist=cytopia-stretch
    - random=0 dist=cytopia-testing
    - random=1 dist=cytopia-testing

before_script:
  # Run it multiple times until it succeeds. This is to prevent errors that occur due to
  # network timeouts between travis-ci
  - max=100; i=0; while [ $i -lt $max ]; do if docker build -t ansible-debian .; then break; else i=$((i+1)); fi done

script:
  # Run it multiple times until it succeeds. This is to prevent errors that occur due to
  # network timeouts between travis-ci
  - max=100; i=0; while [ $i -lt $max ]; do if docker run --rm -e MY_HOST=${dist} -e random=${random} -t ansible-debian; then break; else i=$((i+1)); fi done
