sudo: required

language: python

services:
  - docker

env:
  matrix:
    ###
    ### Generic profile
    ###
    # All roles (playbook order)
    - single=0 random=0 dist=generic-all
    # All roles (random order)
    - single=0 random=1 dist=generic-all
    # Start each role separately
    - single=1 random=0 dist=generic-all

    ###
    ### Cytopia's profile
    ###
    # All roles (playbook order)
    - single=0 random=0 dist=cytopia-t470p
    # All roles (random order)
    - single=0 random=1 dist=cytopia-t470p
    # Start each role separately
    - single=1 random=0 dist=cytopia-t470p


before_script:
  # Run it multiple times until it succeeds. This is to prevent errors that occur due to
  # network timeouts between travis-ci
  - max=100; i=0; while [ $i -lt $max ]; do if docker build -t ansible-debian .; then break; else i=$((i+1)); fi done

script:
  # 1. Run it multiple times until it succeeds. This is to prevent errors that occur due to network timeouts between travis-ci
  # 2. Separate between single runs and full runs
  - if [ "${single}" -eq "1" ]; then
        ROLES="$( for d in $(/bin/ls roles/); do if [ -d roles/${d} ]; then echo $d; fi done | grep -vE '*-meta$' | sort -R )";
        TOTAL="$( echo "${ROLES}" | wc -l )";
        START=1;
        for r in ${ROLES}; do
            printf "========== Run %s / %s (%s) ==========\n" "${START}" "${TOTAL}" "${r}";
            max=10; i=0; while [ $i -lt $max ]; do
                if make test-docker-single PROFILE=${dist} ROLE=${r}; then
                    break;
                else
                    i=$((i+1));
                fi;
            done;
            if [ $i -gt 8 ]; then false; fi;
            START=$((START+1));
        done;
    else
        if [ "${random}" -eq "1" ]; then
            make test-docker-random PROFILE=${dist};
        else
            make test-docker-full PROFILE=${dist};
        fi
    fi
