sudo: required

language: python

services:
  - docker

env:
  matrix:
    - python=2
    - python=3

before_script:
  - docker build -t ansible-debian-python${python} -f Dockerfile.python${python} .

script:
  - docker run --rm -t ansible-debian-python${python}
