---

- name: ensure requirements are installed
  include_role:
    name: apt-meta
  vars:
    apt_packages:
      - fontconfig
      - unzip

- name: fetch ubuntu font info
  uri:
    url: https://design.ubuntu.com/font/
    method: GET
    follow_redirects: yes
    return_content: yes
  register: font_ubuntu_raw
  check_mode: no

- name: set ubuntu font url
  set_fact:
    font_ubuntu_zip: "{{ font_ubuntu_raw.content | regex_search(qry) }}"
  vars:
    qry: 'https://assets.ubuntu.com/.*-ubuntu-font-family-[.0-9]+\.zip'
  check_mode: no

- name: ensure font directory exists
  file:
    path: "{{ font_ubuntu_font_path }}"
    state: directory
    mode: 0755
  notify: update font-cache

- name: ensure ubuntu font is downloaded
  unarchive:
    src: "{{ font_ubuntu_zip }}"
    dest: "{{ font_ubuntu_font_path }}"
    remote_src: yes
    mode: 0755
  notify: update font-cache
