---

python_2: yes
python_3: yes
python_default: 2

python_2_apt_pachages:
  - python
  - python-pip
python_3_apt_pachages:
  - python3
  - python3-pip

python_pip_packages:
  - wheel
  - configparser



