---

- name: ensure thunderbird is removed
  include_role:
    name: apt-meta
  vars:
    apt_state: absent
    apt_packages:
      - "{{ thunderbird_package_name }}"
      - "{{ thunderbird_additional_packages }}"

- name: ensure thunderbird extensions directory is removed
  file:
    state: absent
    path: "{{ thunderbird_ext_dir }}"
  become: Yes
