---

- name: ensure clipmenu requirements are installed
  include_role:
    name: apt-meta
  vars:
    apt_packages:
      - "{{ clipmenu_packages }}"

- name: ensure clipmenu is downloaded
  get_url:
    url: "https://raw.githubusercontent.com/cdown/clipmenu/develop/{{ item }}"
    dest: "{{ clipmenu_bin_path }}/{{ item }}"
    mode: 0755
    force: yes
  become: yes
  with_items:
    - clipmenu
    - clipmenud
