---

- name: ensure ubuntu font directory is removed
  file:
    path: "{{ item.path }}"
    state: absent
  with_items:
    - "{{ font_san_francisco_font_dirs.files | default([]) }}"
  notify: update font-cache
