---

- name: ensure apt packages are managed
  apt:
    state: "{{ apt_state }}"
    name: "{{ item }}"
    update_cache: yes
    cache_valid_time: 3600
    autoclean: yes
    autoremove: yes
    install_recommends: no
  become: yes
  with_items: "{{ apt_packages }}"
