---

- name: ensure apt packages are managed
  apt:
    state: "{{ apt_state }}"
    name: "{{ item }}"
    force_apt_get: yes
    update_cache: yes
    cache_valid_time: 3600
    install_recommends: no
  become: yes
  with_items: "{{ apt_packages }}"
  notify: clean apt
