---

# 'install', 'remove' or 'ignore'
sxiv: 'ignore'

sxiv_mime_types:
  - image/bmp
  - image/gif
  - image/jpeg;
  - image/jpg
  - image/png
  - image/tiff
  - image/x-bmp
  - image/x-portable-anymap
  - image/x-portable-bitmap
  - image/x-portable-graymap
  - image/x-tga
  - image/x-xpixmap
