---

- include_tasks: install.yml
  when: font_terminus == 'install'

- include_tasks: uninstall.yml
  when: font_terminus == 'remove'

# Make sure the handler runs now and not at the end of the playbook
- meta: flush_handlers
