---

- name: ensure sublime text repo is present
  include_role:
    name: apt-repo-meta
  vars:
    apt_repo_keys:
      - "{{ sublime_apt_key }}"
    apt_repo_repositories:
      - "{{ sublime_apt_repo }}"

- name: ensure sublime text is installed
  include_role:
    name: apt-meta
  vars:
    apt_packages:
      - sublime-text
