---

###
### Custom variables
###
debian_dist: stretch



###
### Debian apt repositories
###
apt_repo_repositories:
  - file: debian-main
    repo: "deb http://deb.debian.org/debian {{ debian_dist }} main contrib non-free"
  - file: debian-updates
    repo: "deb http://deb.debian.org/debian {{ debian_dist }}-updates main contrib non-free"
  - file: debian-security
    repo: "deb http://security.debian.org {{ debian_dist }}/updates main contrib non-free"
  - file: debian-backports
    repo: "deb http://deb.debian.org/debian {{ debian_dist }}-backports main contrib non-free"


###
### Systemd services
###
systemd_enabled: []

# https://github.com/Airblader/dotfiles-manjaro/blob/master/SETUP
systemd_disabled:
  - exim4.service
  - ModemManager.services
  - nfs-common.service
  - rpcbind.service
  - rpcbind.target
  - binfmt-support.service


###
### System Python versions
###
python_2: yes
python_3: yes


###
### Debian packages (add your custom packages here)
###
apt_packages:
# ---- Base Utils ----
  - dnsutils
  - gnupg
  - gnupg-agent
  - htop
  - iw
  - keychain
  - less
  - lsb-release
  - lsof
  - man-db
  - manpages
  - moreutils
  - net-tools
  - pinentry-tty
  - pwgen
  - socat
  - tmux
  - traceroute
  - tree
  - wireless-tools
# ---- Sec Tools (default) ----
  - netcat
  - netcat-openbsd
  - nmap
  - wireshark-gtk
# ---- Sec Tools (wireless) ----
  - aircrack-ng
  - horst
  - kismet
  - kismet-plugins
# ---- Theme tools ----
  - lxappearance
  - qt4-qtconfig
# ---- Fonts ----
  - fonts-arphic-ukai
  - fonts-arphic-uming
  - fonts-ipafont-gothic
  - fonts-ipafont-mincho
  - fonts-liberation
  #- fonts-open-sans (requires debian testing)
  - fonts-opensymbol
  - fonts-symbola
  - ttf-mscorefonts-installer
  - ttf-wqy-zenhei
# ---- Firmwares ----
  - intel-microcode
  - firmware-misc-nonfree
  - firmware-linux
  - firmware-iwlwifi
  - firmware-crystalhd
# ---- Window Manager ----
  - arandr
  - compton
  - dunst
  - feh
  - i3lock
  - i3blocks
  - redshift
  - redshift-gtk
  - rofi
  - xss-lock
# ---- Office / Productivity ----
  - pinta
  - gimp
  #- gimp-dcraw (either dcraw or ufraw)
  - gimp-ufraw
  - gnome-calculator
  - keepassx
# ---- Video ----
  - vlc
  - vlc-plugin-notify
  - vlc-plugin-samba
  - x264
  - x265
# ---- Audio ----
  - alsa-utils
  - alsa-oss
  - blueman
  - pavucontrol
  - pulseaudio
  - pulseaudio-module-bluetooth
  - pulseaudio-utils
# ---- Network clients ----
  - jxplorer
  - mariadb-client
  - openssh-client
  - redis-tools
  - remmina
  - remmina-plugin-nx
  - remmina-plugin-rdp
  - remmina-plugin-vnc
  - remmina-plugin-xdmcp
  - swaks
# ---- Development ----
  - ack
  - ack-grep
  - binutils
  - devscripts
  - dos2unix
  - exuberant-ctags
  - pep8
  - php-cli
  - pylint
  - pylint3
  - python-pep8
  - python3-pep8
  - shellcheck
  - silversearcher-ag
  - tig
  - yamllint
# ---- chat ----
  #- weechat
# ---- dbus ----
  #- dbus
  #- dbus-user-session
  #- dbus-x11


###
### Python pip packages (add your custom packages here)
###
pip_packages:
  - awscli
  - aws-adfs


###
### Select packages to install
###
### 'install': Install the package
### 'remove':  Uninstall the package
### Any other value will ignore the package (neither install nor uninstall)

chromium:              'install'
clipmenu:              'install'
dbeaver:               'install'
diff_highlight:        'install'
docker:                'install'
docker_compose:        'install'
firefox:               'install'
font_font_awesome:     'install'
font_droid_sans_mono:  'install'
font_san_francisco:    'install'
font_terminus:         'install'
font_ubuntu:           'install'
fzf:                   'install'
hipchat:               'install'
i3_gaps:               'install'
i3_utils_bin:          'install'
i3_utils_systemd:      'install'
i3blocks_modules:      'install'
icon_moka:             'install'
libreoffice:           'install'
lxdm:                  'install'
neovim:                'install'
network_manager:       'install'
packer:                'install'
ranger:                'install'
skype:                 'install'
sublime:               'install'
sxiv:                  'install'
telegram:              'install'
theme_arc:             'install'
thunar:                'install'
thunar_custom_actions: 'install'
timemachine:           'install'
urxvt:                 'install'
xbacklight:            'install'
xorg:                  'install'
zathura:               'install'


###
### Settings for packages
###

# ---- Docker ----
# 'wheezy', 'jessie', 'stretch' or 'buster'
docker_repo_dist: "{{ debian_dist }}"
# 'stable' or 'edge'
docker_repo_channel: stable

# ---- FZF ----
# Add sourcing ~/.fzf.bash to your normal shell config?
fzf_update_rc: Yes
# Enable/Disable fuzzy completion (bash & zsh)?
fzf_completion: No
# Enable/disable key bindings (CTRL-T, CTRL-R, ALT-C)?
fzf_key_bindings: No

# ---- HipChat ----
# 'wheezy', 'jessie', 'stretch' or 'buster'
hipchat_repo_dist: "{{ debian_dist }}"

# ---- LibreOffice ----
libreoffice_dpi: 120

# ---- LXDM ----
lxdm_dpi: 132
lxdm_gtk_theme: Arc-Darker
lxdm_show_user_list: no

# ---- NetworkManager ----
network_manager_nm_applet: Yes
network_manager_plugin_openvpn: Yes
network_manager_plugin_iodine: No
network_manager_plugin_l2tp: No
network_manager_plugin_openconnect: No
network_manager_plugin_pptp: No
network_manager_plugin_ssh: No
network_manager_plugin_strongswan: No
network_manager_plugin_vpnc: No

# ---- Skype ----
# 'stable' or 'unstable'
skype_repo_channel: stable

# ---- Sublime ----
# 'stable' or 'dev'
sublime_repo_channel: stable

# ---- sxiv ----
# Make sxiv default program for pictures
sxiv_default_image_viewer: yes

# ---- Thunar ----
thunar_volman_enable: yes
thunar_archive_plugin_enable: yes

# ---- Xorg ----
# Supported values: 'amdgpu' 'ati' 'intel' 'modesetting' 'nouveau' 'nvidia' 'radeon'
xorg_gpu: modesetting
# Supported values: 'XAA' 'EXA' 'UXA' 'SNA' 'glamor'
xorg_gpu_accel_method: glamor
# Enable VDPAU_DRIVER=va_gl systemwide
xorg_gpu_vdpau_va_gl_enable: yes
# 'libinput' or 'synaptics'
xorg_touchpad_enable: yes
xorg_touchpad_driver: 'synaptics'


###
### Set your preferred default applications
###
xdg_mime_defaults:
  - desktop_file: Thunar.desktop
    mime_types:
      - inode/directory
  - desktop_file: chromium.desktop
    mime_types:
      - text/html
      - text/xml
      - application/xhtml_xml
      - application/x-mimearchive
      - x-scheme-handler/http
      - x-scheme-handler/https
  - desktop_file: zathura.desktop
    mime_types:
      - application/pdf
      - application/postscript
      - application/eps
      - application/x-eps
      - image/eps
      - image/x-eps
