---

###
### Custom variables
###
debian_dist: stretch



###
### Debian apt repositories
###
apt_repo_repositories:
  - file: debian-main
    repo: "deb http://deb.debian.org/debian {{ debian_dist }} main"
  - file: debian-updates
    repo: "deb http://deb.debian.org/debian {{ debian_dist }}-updates main"
  - file: debian-security
    repo: "deb http://security.debian.org {{ debian_dist }}/updates main"


###
### System Python versions
###
python_2: yes
python_3: yes


###
### Debian packages (add your custom packages here)
###
apt_packages: []


###
### Python pip packages (add your custom packages here)
###
pip_packages: []


###
### Select packages to install
###
### 'install': Install the package
### 'remove':  Uninstall the package
### Any other value will ignore the package (neither install nor uninstall)

chromium:              'install'
clipmenu:              'install'
dbeaver:               'install'
diff_highlight:        'install'
docker:                'install'
docker_compose:        'install'
font_font_awesome:     'install'
font_droid_sans_mono:  'install'
font_san_francisco:    'install'
font_terminus:         'install'
font_ubuntu:           'install'
fzf:                   'install'
hipchat:               'install'
i3_gaps:               'install'
i3_utils_bin:          'install'
i3_utils_systemd:      'install'
i3blocks_modules:      'install'
icon_moka:             'install'
lxdm:                  'install'
neovim:                'install'
network_manager:       'install'
packer:                'install'
ranger:                'install'
skype:                 'install'
sublime:               'install'
sxiv:                  'install'
telegram:              'install'
theme_arc:             'install'
thunar:                'install'
thunar_custom_actions: 'install'
timemachine:           'install'
urxvt:                 'install'
xbacklight:            'install'
xorg:                  'install'
zathura:               'install'


###
### Settings for packages
###

# ---- Docker ----
# 'wheezy', 'jessie', 'stretch' or 'buster'
docker_repo_dist: "{{ debian_dist }}"
# 'stable' or 'edge'
docker_repo_channel: stable

# ---- FZF ----
# Add sourcing ~/.fzf.bash to your normal shell config?
fzf_update_rc: Yes
# Enable/Disable fuzzy completion (bash & zsh)?
fzf_completion: No
# Enable/disable key bindings (CTRL-T, CTRL-R, ALT-C)?
fzf_key_bindings: No

# ---- HipChat ----
# 'wheezy', 'jessie', 'stretch' or 'buster'
hipchat_repo_dist: "{{ debian_dist }}"

# ---- LXDM ----
lxdm_dpi: 96
lxdm_gtk_theme: Industrial
lxdm_show_user_list: no

# ---- NetworkManager ----
network_manager_nm_applet: Yes
network_manager_plugin_openvpn: Yes
network_manager_plugin_iodine: No
network_manager_plugin_l2tp: No
network_manager_plugin_openconnect: No
network_manager_plugin_pptp: No
network_manager_plugin_ssh: No
network_manager_plugin_strongswan: No
network_manager_plugin_vpnc: No

# ---- Skype ----
# 'stable' or 'unstable'
skype_repo_channel: stable

# ---- Sublime ----
# 'stable' or 'dev'
sublime_repo_channel: stable

# ---- sxiv ----
# Make sxiv default program for pictures
sxiv_default_image_viewer: yes

# ---- Thunar ----
thunar_volman_enable: yes
thunar_archive_plugin_enable: yes

# ---- Xorg ----
# Supported values: 'amdgpu' 'ati' 'intel' 'modesetting' 'nouveau' 'nvidia' 'radeon'
xorg_gpu: modesetting
# Supported values: 'XAA' 'EXA' 'UXA' 'SNA' 'glamor'
xorg_gpu_accel_method: glamor
# Enable VDPAU_DRIVER=va_gl systemwide
xorg_gpu_vdpau_va_gl_enable: yes
# 'libinput' or 'synaptics'
xorg_touchpad_enable: yes
xorg_touchpad_driver: 'synaptics'


###
### Set your preferred default applications
###
xdg_mime_defaults:
  - desktop_file: Thunar.desktop
    mime_types:
      - inode/directory
  - desktop_file: chromium.desktop
    mime_types:
      - text/html
      - text/xml
      - application/xhtml_xml
      - application/x-mimearchive
      - x-scheme-handler/http
      - x-scheme-handler/https
  - desktop_file: zathura.desktop
    mime_types:
      - application/pdf
      - application/postscript
      - application/eps
      - application/x-eps
      - image/eps
      - image/x-eps
