---

- name: ensure either python2 or python3 is enabled
  assert:
    that:
      - python_2 or python_3
    msg: either python2 or python3 must be enabled (or both)

- name: ensure that python default version is enabled
  assert:
    that:
      - (python_default == 2 and python_2) or (python_default == 3 and python_3)
    msg: selected python default version must also be enabled to install

- name: ensure python2 packages are installed
  include_role:
    name: apt-meta
  vars:
    apt_packages:
      - "{{ python_2_apt_packages }}"
  when: python_2

- name: ensure python3 packages are installed
  include_role:
    name: apt-meta
  vars:
    apt_packages:
      - "{{ python_3_apt_packages }}"
  when: python_3

- name: ensure python default version is set
  alternatives:
    name: python
    link: /usr/bin/python
    path: "/usr/bin/python{{ python_default }}"
    priority: 1
  become: yes

- name: ensure python2 pip packages are installed
  pip:
    state: latest
    name: "{{ item }}"
    executable: pip2
  become: yes
  when: python_2
  with_items:
    - "{{ python_pip_packages }}"
    - "{{ pip_packages }}"

- name: ensure python3 pip packages are installed
  pip:
    state: latest
    name: "{{ item }}"
    executable: pip3
  become: yes
  when: python_3
  with_items:
    - "{{ python_pip_packages }}"
    - "{{ pip_packages }}"
