---

###
### Install test
###
- hosts: localhost
  roles:
    - apt-repo-meta
    - apt-meta

- hosts: localhost
  roles:
    - diff-highlight
    - font-ubuntu
    - docker
    - docker-compose
    - skype
    - sublime
    - hipchat
    - i3_utils_bin

###
### Uninstall test (reverse order)
###
- hosts: localhost
  vars:
    diff_highlight: 'remove'
    font_ubuntu: 'remove'
    docker: 'remove'
    docker_compose: 'remove'
    skype: 'remove'
    sublime: 'remove'
    hipchat: 'remove'
    i3_utils_bin: 'remove'
  roles:
    - diff-highlight
    - font-ubuntu
    - docker
    - docker-compose
    - skype
    - sublime
    - hipchat
    - i3_utils_bin

- hosts: localhost
  vars:
    apt_repo_state: absent
  roles:
    - apt-meta
    - apt-repo-meta
